export const LOG_IN = 'LOG_IN';
export const GET_USER_DATA = 'GET_USER_DATA';
export const RECEIVE_LOGINDATA = 'RECEIVE_LOGINDATA';
export const ERROR_LOGINDATA = 'ERROR_LOGINDATA';
export const GET_ERROR_FALSE = 'GET_LOGIN_FALSE';