export const LOG_IN = 'LOG_IN';
export const GET_USER_DATA = 'GET_USER_DATA';
export const RECEIVE_LOGIN_DATA = 'RECEIVE_LOGIN_DATA';
export const ERROR_LOGIN_DATA = 'ERROR_LOGIN_DATA';
export const GET_ERROR_FALSE = 'GET_LOGIN_FALSE';