export const SET_ADDED_SCHEDULE_NAME = 'SET_ADDED_SCHEDULE_NAME';
export const ADD_WORKLOAD = 'ADD_WORKLOAD';
export const SET_SELECTED_LOAD = 'SET_SELECTED_LOAD';
export const FILL_SCHEDULE_CELL = 'FILL_SCHEDULE_CELL';
